[package]
name = "lantern"
version = "0.1.0"
authors = ["Artem Chistyakov <chistyakov.artem@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.8"
actix-web = "1.0"
actix-web-actors = "1.0"