version: 2.0
jobs:
  build_x86_64:
    working_directory: /checkout
    docker:
      - image: temochka/lantern-build:amd64
    steps:
      - checkout
      - run: ./scripts/release.sh x86_64-unknown-linux-musl
      - persist_to_workspace:
          root: ./artifacts
          paths:
            - '*'
  release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      - attach_workspace:
          at: ./artifacts
      - run: ./scripts/publish.sh ${CIRCLE_TAG}

workflows:
  version: 2
  build:
    jobs:
      - build_x86_64
      - release:
          filters:
            branches:
              only: main
          requires:
            - build_x86_64
