version: 2.0
jobs:
  build_x86_64:
    working_directory: /checkout
    docker:
      - image: temochka/lantern-build:amd64
    steps:
      - checkout
      - attach_workspace:
          at: ./artifacts
      - run: ./scripts/release.sh ${CIRCLE_TAG:-dev} x86_64-unknown-linux-musl
  build_i686:
    working_directory: /checkout
    docker:
      - image: temochka/lantern-build:i386
    steps:
      - checkout
      - attach_workspace:
          at: ./artifacts
      - run: ./scripts/release.sh ${CIRCLE_TAG:-dev} i686-unknown-linux-musl
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./artifacts

workflows:
  version: 2
  build:
    jobs:
      - build_x86_64:
          filters:
            tags:
              only: /.*/
      - build_i686:
          filters:
            tags:
              only: /.*/
      - publish-github-release:
          filters:
            tags:
              only: /^v.*/
          requires:
            - build_x86_64
            - build_i686
