version: 2.0
jobs:
  build_x86_64:
    working_directory: /checkout
    docker:
      - image: temochka/lantern-build:amd64
    steps:
      - checkout
      - run: ./scripts/release.sh x86_64-unknown-linux-musl
      - persist_to_workspace:
          root: ./artifacts
          paths:
            - '*'
  build_i686:
    working_directory: /checkout
    docker:
      - image: temochka/lantern-build:i386
    steps:
      - checkout
      - run: ./scripts/release.sh i686-unknown-linux-musl
      - persist_to_workspace:
          root: ./artifacts
          paths:
            - '*'
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_SHA1} ./artifacts

workflows:
  version: 2
  build:
    jobs:
      - build_x86_64
      - build_i686
      - publish-github-release:
          filters:
            branches:
              only: master
          requires:
            - build_x86_64
            - build_i686
